In [4]:
# To find rank of the matrix
import numpy as np
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])
R = np.linalg.matrix_rank(mx)
print(mx)
print("The Rank of the Matrix is :",R)

[[1 1 1]
 [0 1 2]
 [1 5 3]]
The Rank of the Matrix is : 3


In [9]:
# TO find solutions of homogeneous linear equations
from sympy import *
x,y,z =symbols('x,y,z')
n = int(input("Enter the number of unknowns: "))
a11,a12,a13 = 1,3,-2
a21,a22,a23 = 2,-1,4
a31,a32,a33 = 1,-11,14
A = Matrix(([a11,a12,a13],[a21,a22,a23],[a31,a32,a33]))
ra = A.rank()
print("The rank of matrix A is: ",ra)
if(ra == n):
    print("The system has only trivial solution")
else:
    print("The system has non-trivial solution ")
    print(linsolve([a11*x+a22*y+a13*z,a21*x+a22*y+a23*z+a31*x+a32*y+a33*z],[x,y,z]))

The rank of matrix A is:  2
The system has non-trivial solution 
{(14*z/3, 8*z/3, z)}
